### ISSUE TITLE
[BUG] [ssps] 403 Forbidden

### ISSUE THREAD

**Issue by Denio21** [cajthamlmatej/SchoolDiscordBot#186]
**Describe the bug**
If you send an event with an attachment, the event is not saved or sent. Error forbidden 403 occurs.
**Branch / version**
SSPS

**To Reproduce**
Start event create subcommand. Fillout everything send attachment with it. Nothing happends.

**Comment by cajthamlmatej** [comment]
Discord broken everything, for now, closing.
