### ISSUE TITLE
Upcoming events

### ISSUE THREAD

**Issue by Denio21** [cajthamlmatej/SchoolDiscordBot#92]
Add function, that reminds you about upcoming events to DM (Sorted by role)

**Comment by cajthamlmatej** [comment]
We need way how to disable this per-user.

**Comment by Denio21** [comment]
We can meake something like blacklist for users. Blacklist will be filtered when are notifications send. We should do command to adding user to "blacklist".

**Comment by cajthamlmatej** [comment]
I would rather make db entity for per-user setting. We can add RSS token to that entity and bool of "send-event-annoucement". (So we could remove directbakalari entity). You can do this. You can practice your mongodb (mongoose) experience here.

**Comment by Denio21** [comment]
Closed bois
